/// This file only holds the template that is used to generate a default .tools.toml.

pub const CONFIG_TEMPLATE: &str = r##"# This file was automatically generated by tool-sync
#
# The directory to store all tools in
#store_directory = "$HOME/.local/bin"
#
#[ripgrep]
#   owner     = "BurntSushi"
#   repo      = "ripgrep"
#   exe_name  = "rg"
#
#   # Uncomment to download a specific version or tag.
#   # Without this tag latest will be used
#   # tag       = "latest"
#
#
# Asset name to download on linux OSes
#asset_name.linux = "x86_64-unknown-linux-musl"
#
# uncomment if you want to install on macOS as well
#asset_name.macos = "apple-darwin"
#
# uncomment if you want to install on Windows as well
#asset_name.windows = "x86_64-pc-windows-msvc"
"##;
