name: Rust

on:
  pull_request:
    types: [synchronize, opened, reopened]
  push:
    branches: [main]
  schedule:
    # additionally run once per week (At 00:00 on Sunday) to maintain cache
    - cron: '0 0 * * 0'

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    name: ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]

    steps:
    - uses: actions/checkout@v3

    - uses: actions/cache@v3
      name: Cache ./target
      with:
        path: target
        key: ${{ runner.os }}-${{ hashFiles('Cargo.lock') }}

    - name: Build
      run: cargo build --verbose

    - name: Unit tests
      run: cargo test --verbose
    
    - name: "Integration test: [only-ripgrep]"
      env:
          SYNC_DIR: "only-ripgrep"
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
          mkdir $SYNC_DIR
          cargo run -- --config=tests/$SYNC_DIR.toml sync

          if [[ ! -x $SYNC_DIR/rg ]]; then echo "error on: rg"; false; fi

    - name: "Integration test: [full-database]"
      env:
          SYNC_DIR: "full-database"
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
          mkdir $SYNC_DIR
          cargo run -- --config=tests/$SYNC_DIR.toml sync

          if [[ ! -x $SYNC_DIR/bat   ]]; then echo "error on: bat";   false; fi
          if [[ ! -x $SYNC_DIR/difft ]]; then echo "error on: difft"; false; fi
          if [[ ! -x $SYNC_DIR/exa   ]]; then echo "error on: exa";   false; fi
          if [[ ! -x $SYNC_DIR/fd    ]]; then echo "error on: fd";    false; fi
          if [[ ! -x $SYNC_DIR/rg    ]]; then echo "error on: rg";    false; fi
          if [[ ! -x $SYNC_DIR/tokei ]]; then echo "error on: tokei"; false; fi
