name: Rust

on:
  pull_request:
    types: [synchronize, opened, reopened]
  push:
    branches: [main]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Build
      run: cargo build --verbose

    - name: Unit tests
      run: cargo test --verbose
    
    - name: "Integration test: [only-ripgrep]"
      env:
          SYNC_DIR: "only-ripgrep"
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
          mkdir $SYNC_DIR
          cargo run -- --config=tests/$SYNC_DIR.toml sync
          test -f $SYNC_DIR/rg

    - name: "Integration test: [full-database]"
      env:
          SYNC_DIR: "full-database"
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
          mkdir $SYNC_DIR
          cargo run -- --config=tests/$SYNC_DIR.toml sync

          test -f $SYNC_DIR/bat
          test -f $SYNC_DIR/difft
          test -f $SYNC_DIR/exa
          test -f $SYNC_DIR/fd
          test -f $SYNC_DIR/rg
          test -f $SYNC_DIR/tokei
