name: Rust

on:
  pull_request:
    types: [synchronize, opened, reopened]
  push:
    branches: [main]
  schedule:
    # additionally run once per week (At 00:00 on Sunday) to maintain cache
    - cron: '0 0 * * 0'

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    name: ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]

    steps:
    - uses: actions/checkout@v3

    - uses: actions/cache@v3
      name: Cache ./target
      with:
        path: target
        key: ${{ runner.os }}-${{ hashFiles('Cargo.lock') }}

    - name: Build
      run: cargo build --verbose

    - name: Unit tests
      run: cargo test --verbose
    
    - if: matrix.os != 'windows-latest'
      name: "Integration test: [unix] [only-ripgrep]"
      env:
          SYNC_DIR: "only-ripgrep"
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
          mkdir $SYNC_DIR
          cargo run -- --config=tests/$SYNC_DIR.toml sync

          ls -l $SYNC_DIR

          if [[ ! -x $SYNC_DIR/rg ]]; then echo "error on: rg"; false; fi

    - if: matrix.os == 'windows-latest'
      name: "Integration test: [windows] [only-ripgrep]"
      env:
          SYNC_DIR: "only-ripgrep"
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
          mkdir $env:SYNC_DIR
          cargo run -- --config="tests\$env:SYNC_DIR.toml" sync

          echo "Before directory..."
          ls -l $env:SYNC_DIR
          echo "After directory..."

          if (!(Test-Path $env:SYNC_DIR\rg.exe)) {
              throw 'error on rg.exe'
          }

    - if: matrix.os != 'windows-latest'
      name: "Integration test: [full-database]"
      env:
          SYNC_DIR: "full-database"
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
          mkdir $SYNC_DIR
          cargo run -- --config=tests/$SYNC_DIR.toml sync

          ls -l $SYNC_DIR

          if [[ ! -x $SYNC_DIR/bat   ]]; then echo "error on: bat";   false; fi
          if [[ ! -x $SYNC_DIR/difft ]]; then echo "error on: difft"; false; fi
          if [[ ! -x $SYNC_DIR/exa   ]]; then echo "error on: exa";   false; fi
          if [[ ! -x $SYNC_DIR/fd    ]]; then echo "error on: fd";    false; fi
          if [[ ! -x $SYNC_DIR/rg    ]]; then echo "error on: rg";    false; fi
          
          # disabled because of: https://github.com/alexcrichton/tar-rs/issues/295
          # if [[ ! -x $SYNC_DIR/tokei ]]; then echo "error on: tokei"; false; fi
